### ISSUE TITLE
data creation

### ISSUE THREAD

**Issue by Asifdotexe** [Asifdotexe/SpamDetection#1]
# To-do list
- [x] Creating a virtual environment
- [x] Created a project scaffolding
- [x] Combining multiple datasets to create a master data
